version: 2.1
orbs:
  cypress: cypress-io/cypress@2
workflows:
  build:
    jobs:
      steps:
        - checkout
        - run:
            name: Running E2E tests
            command: npx cypress run
        - store_artifacts:
            path: cypress/videos
        - store_artifacts:
            path: cypress/screenshots
